apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello-kubernetes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-kubernetes.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.container.image.repository }}:{{ .Values.deployment.container.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.container.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.container.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          {{- if ne (.Values.deployment.container.port | int) (8080 | int) }}
          - name: PORT
            value: "{{ .Values.deployment.container.port }}"
          {{- end }}
          {{- if .Values.message }}
          - name: MESSAGE
            value: "{{ .Values.message }}"
          {{- end }}
          {{- if .Values.ingress.enabled }}
          - name: CONTEXT_PATH
            value: "{{ .Values.ingress.pathPrefix }}"
          {{- end }}
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
